### ISSUE TITLE
Submission checklist:

### ISSUE THREAD

**Issue by HemingNM** [gabferreira/phyloraster#1]
TO DOs:
- [x] reduce size of example files
- [x] reduce size of test files
- [x] remove `vec.*()` functions. No longer needed.
- [x] remove argument `cores` from functions that do not use `terra::app()` anymore. Probably all.
- [x] add `#' @keywords internal` to the documentation of all functions with names starting with "dot"
- [x] check all function examples (mostly update `inv.range()` arguments). Use `devtools::run_examples()`
- [x] `epm` tests should run using a raster instead of using dependency package. Create raster using epm, save script in "data-raw" folder and tiff in "inst/extdata" folder. See: [SESraster](https://github.com/HemingNM/SESraster/tree/master/data-raw/)
- [x] remove `rnaturalearth` dependency creating custom polygons. See `terra::vect()`
- [x] add option to compute tree metrics (branch.length, n.descen) from full tree or subset
- [x] organize README according to [SESraster](https://github.com/HemingNM/SESraster/blob/master/README.md)
- [x] CRAN like check: `devtools::check(remote = TRUE, manual = TRUE)`
- [x] organize vignettes and README
- [x] update "hexalogo"
- [x] set up pkgdown website
